name: CI

'on':
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./  # use currently-checked out files
          file: ./Dockerfile
          push: true
          tags: localhost:5000/spherex/spherex-tex:latest

      - name: Run tests
        working-directory: ./
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace localhost:5000/spherex/spherex-tex:latest sh -c 'cd test && ./test.sh'

      - uses: actions/upload-artifact@v2
        with:
          name: pipeline_module-ssdc-ms-000.pdf
          path: test/pipeline_module/ssdc-ms-000.pdf
          retention-days: 7
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        with:
          name: pipeline_module_unapproved-ssdc-ms-000.pdf
          path: test/pipeline_module_unapproved/ssdc-ms-000.pdf
          retention-days: 7
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        with:
          name: technote-ssdc-tn-000.pdf
          path: test/technote/ssdc-tn-000.pdf
          retention-days: 7
          if-no-files-found: error
